# Generated by Django 4.2.1 on 2023-06-07 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0002_category_category_icon_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='category_image',
            field=models.ImageField(default='category/category.png', upload_to='category/', verbose_name='Главное изображение категории'),
        ),
    ]
