# Generated by Django 4.2.1 on 2023-06-05 23:28

from django.db import migrations, models
import django.db.models.deletion
import main.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('category', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Название продукта')),
                ('product_slug', models.SlugField(blank=True, unique=True)),
                ('card_title', models.CharField(max_length=100, verbose_name='Титульник карточки')),
                ('price', models.IntegerField(verbose_name='Цена')),
                ('brand_name', models.CharField(max_length=100, verbose_name='Название бренда')),
                ('description', models.TextField(verbose_name='Описание')),
                ('product_main_img', models.ImageField(upload_to=main.models.upload_to, verbose_name='Главное изображение продукта')),
                ('main_category', models.ForeignKey(default='Main category', null=True, on_delete=django.db.models.deletion.CASCADE, to='category.category')),
                ('main_subcategory', models.ForeignKey(default='Subcategory', null=True, on_delete=django.db.models.deletion.CASCADE, to='category.subcategory')),
            ],
        ),
        migrations.CreateModel(
            name='ImageModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=main.models.upload_to_images)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='thumbnail_images', to='main.product')),
            ],
        ),
    ]
