# Generated by Django 4.2.1 on 2023-06-27 15:42

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import main.models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0001_initial'),
        ('main', '0002_remove_user_form_submitted'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='available',
            field=models.BooleanField(default=True, verbose_name='Available'),
        ),
        migrations.AddField(
            model_name='product',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Created time'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='uploaded',
            field=models.DateTimeField(auto_now=True, verbose_name='Uploaded time'),
        ),
        migrations.AlterField(
            model_name='product',
            name='brand_name',
            field=models.CharField(blank=True, default='Brand name', max_length=100, verbose_name='Brand name'),
        ),
        migrations.AlterField(
            model_name='product',
            name='card_title',
            field=models.CharField(blank=True, default='Card title', max_length=100, verbose_name='Card title'),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True, default='Description', max_length=1500, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='product',
            name='main_category',
            field=models.ForeignKey(default='Category', null=True, on_delete=django.db.models.deletion.CASCADE, to='category.category', verbose_name='Subcategory'),
        ),
        migrations.AlterField(
            model_name='product',
            name='main_subcategory',
            field=models.ForeignKey(default='Subcategory', null=True, on_delete=django.db.models.deletion.CASCADE, to='category.subcategory', verbose_name='Category'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Price'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_main_img',
            field=models.ImageField(upload_to=main.models.upload_to, verbose_name='Product main image'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_slug',
            field=models.SlugField(editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='title',
            field=models.CharField(db_index=True, max_length=100, verbose_name='Product title'),
        ),
    ]
