# Generated by Django 4.2.1 on 2023-06-28 07:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0001_initial'),
        ('main', '0003_product_available_product_created_product_uploaded_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='main_category',
            field=models.ForeignKey(default='Category', null=True, on_delete=django.db.models.deletion.CASCADE, to='category.category', verbose_name='Category'),
        ),
        migrations.AlterField(
            model_name='product',
            name='main_subcategory',
            field=models.ForeignKey(default='Subcategory', null=True, on_delete=django.db.models.deletion.CASCADE, to='category.subcategory', verbose_name='SubCategory'),
        ),
    ]
