# Generated by Django 4.2.1 on 2023-07-05 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_product_main_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='favorite',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
